import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const THEMES = [
  { key: "frutas", name: "Frutas" },
  { key: "cor", name: "Cor" },
  { key: "raca_cachorro", name: "Raça de Cachorros" },
  { key: "filmes", name: "Filmes" },
  { key: "novelas_series", name: "Novelas e Séries" },
  { key: "cep", name: "CEP (Cidade, Estado, País)" },
  { key: "elementos_quimicos", name: "Elementos Químicos" },
  { key: "nomes_pessoas", name: "Nomes de Pessoas" },
  { key: "times_futebol", name: "Times de Futebol" },
  { key: "bandas_musicais", name: "Bandas Musicais" },
  { key: "instrumentos_musicais", name: "Instrumentos Musicais" },
  { key: "profissao", name: "Profissão" },
];

const SEED_WORDS = {
  frutas: {
    A: ["Abacaxi", "Abacate", "Acerola", "Amora"],
    B: ["Banana"],
    C: ["Caju", "Cereja", "Coco", "Carambola", "Cupuaçu"],
    D: ["Damasco"],
    F: ["Figo", "Framboesa"],
    G: ["Goiaba", "Graviola", "Groselha"],
    J: ["Jaca", "Jabuticaba", "Jambo"],
    L: ["Laranja", "Limão", "Lichia"],
    M: ["Maçã", "Manga", "Mamão", "Melancia", "Melão", "Morango", "Maracujá"],
    N: ["Nectarina"],
    P: ["Pera", "Pêssego", "Pitaya", "Pinha", "Physalis"],
    R: ["Romã"],
    T: ["Tangerina", "Tamarindo", "Toranja"],
    U: ["Uva"],
  },
  cor: {
    A: ["Azul", "Amarelo", "Âmbar", "Anil"],
    B: ["Bege", "Branco", "Bordô"],
    C: ["Ciano", "Cinza", "Coral"],
    D: ["Dourado"],
    L: ["Laranja", "Lilás"],
    M: ["Magenta", "Marrom"],
    P: ["Preto", "Púrpura", "Pink", "Prata"],
    R: ["Roxo", "Rosa"],
    T: ["Turquesa"],
    V: ["Verde", "Vermelho", "Violeta"],
  },
  raca_cachorro: {
    A: ["Akita", "Airedale"],
    B: ["Beagle", "Buldogue", "Boxer", "Basset"],
    C: ["Chihuahua", "Collie", "Cocker Spaniel"],
    D: ["Dálmata", "Doberman"],
    F: ["Fila Brasileiro"],
    G: ["Golden Retriever", "Galgo"],
    H: ["Husky Siberiano"],
    L: ["Labrador", "Lhasa Apso"],
    M: ["Maltês", "Mastiff"],
    P: ["Pug", "Poodle", "Pinscher", "Pastor Alemão", "Pequinês"],
    R: ["Rottweiler"],
    S: ["Shih Tzu", "Spitz Alemão", "São Bernardo"],
    T: ["Terrier"],
    V: ["Vira-lata"],
  },
  filmes: {
    A: ["Avatar", "Amadeus"],
    B: ["Batman"],
    C: ["Coringa", "Casablanca"],
    D: ["Duna"],
    E: ["Elysium"],
    G: ["Gladiador", "Gravidade"],
    H: ["Hancock"],
    I: ["Interestelar"],
    J: ["Jumanji"],
    L: ["La La Land"],
    M: ["Matrix", "Minions"],
    N: ["Nemo"],
    O: ["Oppenheimer"],
    P: ["Parasita"],
    R: ["Rocky"],
    S: ["Shrek"],
    T: ["Titanic", "Tubarão", "Thor"],
    U: ["Up"],
    V: ["Vingadores"],
    X: ["X-Men"],
    Z: ["Zorro", "Zootopia"],
  },
  novelas_series: {
    A: ["Avenida Brasil"],
    B: ["Breaking Bad"],
    C: ["Chaves"],
    D: ["Dark"],
    F: ["Friends", "Fauda"],
    G: ["Game of Thrones", "Grey's Anatomy"],
    H: ["House"],
    L: ["Lost"],
    M: ["Malhação", "Merlí"],
    N: ["Narcos"],
    O: ["O Rei do Gado"],
    P: ["Prison Break"],
    R: ["Rebelde"],
    S: ["Stranger Things"],
    T: ["Twin Peaks", "The Office"],
    V: ["Vale Tudo"],
    X: ["Xena: A Princesa Guerreira"],
  },
  cep: {
    A: ["Aracaju", "Argentina", "Alemanha"],
    B: ["Belém", "Brasília", "Bahia", "Bolívia"],
    C: ["Curitiba", "Chile", "Canadá"],
    E: ["Espírito Santo", "Egito"],
    F: ["Fortaleza", "França"],
    G: ["Goiânia"],
    I: ["Itália", "Irlanda"],
    J: ["Japão"],
    L: ["Londres"],
    M: ["Maceió", "México", "Manaus"],
    N: ["Natal", "Noruega"],
    P: ["Porto Alegre", "Paris", "Peru", "Portugal"],
    R: ["Rio de Janeiro", "Recife"],
    S: ["São Paulo", "Salvador", "Sorocaba", "Suécia"],
    T: ["Teresina", "Tóquio"],
    U: ["Uruguai"],
    V: ["Vitória", "Vietnã"],
    X: ["Xangai"],
    Z: ["Zâmbia", "Zimbábue"],
  },
  elementos_quimicos: {
    A: ["Alumínio", "Argônio"],
    B: ["Bário", "Boro", "Bromo"],
    C: ["Carbono", "Cálcio", "Cobre", "Cloro", "Cromo"],
    E: ["Enxofre", "Estanho"],
    F: ["Ferro", "Flúor", "Fósforo"],
    G: ["Gálio"],
    H: ["Hidrogênio", "Hélio"],
    I: ["Iodo", "Ítrio"],
    L: ["Lítio"],
    M: ["Magnésio", "Manganês", "Mercúrio"],
    N: ["Nitrogênio", "Neônio", "Níquel"],
    O: ["Oxigênio", "Ouro"],
    P: ["Potássio", "Platina", "Prata"],
    R: ["Rádio", "Radônio"],
    S: ["Sódio", "Silício", "Selênio"],
    T: ["Titânio", "Tungstênio"],
    U: ["Urânio"],
    V: ["Vanádio"],
    X: ["Xenônio"],
    Z: ["Zinco", "Zircônio"],
  },
  nomes_pessoas: {
    A: ["Ana", "André", "Alice", "Antônio"],
    B: ["Bruno", "Beatriz", "Bianca"],
    C: ["Carlos", "Camila", "Caio", "Cláudia"],
    D: ["Daniel", "Diana", "Diego"],
    E: ["Eduardo", "Elisa"],
    F: ["Felipe", "Fernanda"],
    G: ["Gabriel", "Giovanna"],
    H: ["Helena", "Henrique"],
    I: ["Igor", "Isabela"],
    J: ["João", "Julia", "Joana"],
    L: ["Lucas", "Larissa", "Leonardo"],
    M: ["Marcos", "Maria", "Mariana", "Miguel"],
    N: ["Natália", "Nicolas"],
    O: ["Otávio"],
    P: ["Paulo", "Patrícia", "Pedro"],
    R: ["Rafael", "Renata", "Ricardo"],
    S: ["Sofia", "Sérgio"],
    T: ["Tiago", "Tatiana"],
    U: ["Úrsula"],
    V: ["Vitor", "Vanessa"],
    X: ["Xavier"],
    Z: ["Zoe", "Zeca", "Zilda"],
  },
  times_futebol: {
    A: ["Atlético Mineiro", "Athletico Paranaense"],
    B: ["Botafogo", "Bahia"],
    C: ["Corinthians", "Cruzeiro", "Ceará"],
    F: ["Flamengo", "Fluminense"],
    G: ["Grêmio"],
    I: ["Internacional"],
    P: ["Palmeiras", "Ponte Preta"],
    R: ["Real Madrid"],
    S: ["Santos", "São Paulo", "Sport"],
    V: ["Vasco", "Vitória"],
  },
  bandas_musicais: {
    A: ["AC/DC", "Aerosmith"],
    B: ["Beatles"],
    C: ["Coldplay"],
    D: ["Deep Purple"],
    E: ["Eagles"],
    F: ["Foo Fighters"],
    G: ["Guns N' Roses"],
    I: ["Iron Maiden"],
    J: ["Journey"],
    L: ["Legião Urbana"],
    M: ["Metallica", "Muse"],
    N: ["Nirvana"],
    O: ["Oasis"],
    P: ["Pink Floyd", "Pearl Jam"],
    Q: ["Queen"],
    R: ["Rush", "Radiohead", "RBD"],
    S: ["Skank"],
    T: ["Titãs"],
    U: ["U2"],
    V: ["Van Halen"],
    X: ["X Japan", "Xutos & Pontapés"],
    Z: ["ZZ Top"],
  },
  instrumentos_musicais: {
    A: ["Atabaque", "Afoxé", "Agogô"],
    B: ["Batá", "Bateria", "Bloco Sonoro", "Bongo"],
    C: ["Caixa", "Caixa de Rufo", "Caneca", "Castanhola"],
    D: ["Djembe"],
    F: ["Flauta"],
    G: ["Gongo", "Guitarra", "Gaita"],
    H: ["Harpa"],
    L: ["Lira"],
    M: ["Marimba"],
    O: ["Oboé", "Órgão"],
    P: ["Piano", "Prato"],
    R: ["Reco-reco"],
    S: ["Saxofone"],
    T: ["Trompete", "Tambor", "Triângulo", "Trompa"],
    V: ["Violino", "Violão", "Viola", "Violoncelo"],
    X: ["Xilofone"],
  },
  profissao: {
    A: ["Astronauta"],
    B: ["Biólogo"],
    C: ["Corredor", "Carteiro"],
    D: ["Digitador", "Dentista"],
    E: ["Estagiário"],
    F: ["Ferreiro"],
    G: ["Geologista", "Garimpeiro"],
    H: ["Hoteleiro"],
    I: ["Inspetor"],
    J: ["Judoca", "Jornalista", "Jornaleiro"],
    L: ["Lavrador"],
    M: ["Maquinista", "Marceneiro"],
    N: ["Nadador"],
    O: ["Operário"],
    P: ["Professor"],
    Q: ["Quitandeiro"],
    R: ["Radialista"],
    S: ["Socorrista", "Sanfoneiro"],
    T: ["Tatuador"],
    U: ["Urologista"],
    V: ["Vereador"],
    X: ["Xerife"],
    Z: ["Zoólogo", "Zootecnista"],
  },
};

async function main() {
  const adminPassword = await bcrypt.hash("admin123", 10);
  await prisma.user.upsert({
    where: { email: "admin@educaogamer.com" },
    update: {},
    create: {
      nickname: "AdminEG",
      email: "admin@educaogamer.com",
      password: adminPassword,
      role: "ADMIN",
    },
  });

  for (const t of THEMES) {
    const theme = await prisma.theme.upsert({
      where: { key: t.key },
      update: {},
      create: t,
    });

    const wordMap = SEED_WORDS[t.key] || {};
    for (const [letter, words] of Object.entries(wordMap)) {
      for (const word of words) {
        await prisma.wordEntry.upsert({
          where: { themeId_letter_word: { themeId: theme.id, letter, word } },
          update: {},
          create: { themeId: theme.id, letter, word, status: "approved" },
        });
      }
    }
  }

  console.log("Seed concluído. Login admin: admin@educaogamer.com / admin123");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
