// Seed do banco de perguntas do Quiz. Roda separado do seed principal
// (npm run prisma:seed:quiz), pra não misturar com os temas/palavras do Stop.
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const QUESTIONS = {
  esportes: [
    { question: "Em que esporte se usa uma raquete e uma peteca?", answer: "Badminton" },
    { question: "Qual país sediou a Copa do Mundo de 2014?", answer: "Brasil" },
    { question: "Quantos jogadores um time de futebol tem em campo?", answer: "Onze" },
    { question: "Qual é o esporte mais popular do mundo?", answer: "Futebol" },
    { question: "Em que esporte Michael Jordan é uma lenda?", answer: "Basquete" },
    { question: "Quantos tempos tem uma partida de futebol?", answer: "Dois" },
    { question: "Em que cidade brasileira aconteceram as Olimpíadas de 2016?", answer: "Rio de Janeiro" },
    { question: "Qual esporte é jogado numa quadra com rede alta, sem a bola tocar o chão?", answer: "Volei" },
    { question: "Qual é o principal troféu do futebol mundial, disputado a cada 4 anos?", answer: "Copa do Mundo" },
    { question: "Em que esporte times competem numa piscina, arremessando uma bola pra um gol?", answer: "Polo Aquatico" },
    { question: "Qual é o estádio de futebol mais famoso do Rio de Janeiro?", answer: "Maracana" },
    { question: "Em que esporte se usa um taco para acertar uma bola pequena em buracos num campo verde?", answer: "Golfe" },
    { question: "Qual jogador brasileiro é conhecido como o 'Rei do Futebol'?", answer: "Pele" },
    { question: "Qual esporte envolve corrida e salto sobre barreiras numa pista?", answer: "Atletismo" },
    { question: "Qual é o principal evento multiesportivo do mundo, realizado a cada 4 anos?", answer: "Jogos Olimpicos" },
    { question: "Em que esporte o atleta usa uma prancha para deslizar sobre as ondas do mar?", answer: "Surfe" },
    { question: "Qual esporte é jogado numa mesa pequena, com raquetes e uma bolinha leve?", answer: "Tenis de Mesa" },
    { question: "Em que esporte os atletas usam luvas e trocam socos dentro de um ringue?", answer: "Boxe" },
    { question: "Quantos anéis tem o símbolo olímpico?", answer: "Cinco" },
    { question: "Qual esporte brasileiro mistura luta, dança e música, criado por escravizados?", answer: "Capoeira" },
    { question: "Em que esporte o atleta nada, pedala e corre numa mesma prova?", answer: "Triatlo" },
    { question: "Qual país é considerado o berço do futebol moderno?", answer: "Inglaterra" },
    { question: "Qual esporte usa uma bola oval e permite o uso das mãos, muito popular nos EUA?", answer: "Futebol Americano" },
    { question: "Em que superfície é disputado o tradicional torneio de tênis de Wimbledon?", answer: "Grama" },
    { question: "Quantos sets, no máximo, pode ter uma partida de vôlei?", answer: "Cinco" },
    { question: "Como se chama o movimento da ginástica em que o atleta gira o corpo no ar?", answer: "Mortal" },
    { question: "Em que esporte as partidas acontecem numa pista de gelo, com patins e tacos?", answer: "Hoquei no Gelo" },
    { question: "Além dos Estados Unidos e do Canadá, qual outro país sediará a Copa do Mundo de 2026?", answer: "Mexico" },
    { question: "Em que esporte o atleta fica em pé numa prancha com vela, usando a força do vento?", answer: "Windsurfe" },
    { question: "Quantos jogadores um time de vôlei tem em quadra?", answer: "Seis" },
  ],
  ciencias: [
    { question: "Qual é o menor planeta do sistema solar?", answer: "Mercurio" },
    { question: "Qual gás os humanos precisam respirar pra viver?", answer: "Oxigenio" },
    { question: "Quem propôs a teoria da relatividade?", answer: "Einstein" },
    { question: "Qual órgão do corpo humano bombeia o sangue?", answer: "Coracao" },
    { question: "Qual é o maior órgão do corpo humano?", answer: "Pele" },
    { question: "Qual cientista formulou a lei da gravidade?", answer: "Newton" },
    { question: "Qual é a fórmula química da água?", answer: "H2O" },
    { question: "Qual é o planeta conhecido como planeta vermelho?", answer: "Marte" },
    { question: "Qual gás as plantas liberam durante a fotossíntese?", answer: "Oxigenio" },
    { question: "Como se chama a célula reprodutiva masculina?", answer: "Espermatozoide" },
    { question: "Qual é o maior planeta do sistema solar?", answer: "Jupiter" },
    { question: "Qual gás as plantas absorvem do ar durante a fotossíntese?", answer: "Dioxido de Carbono" },
    { question: "Qual cientista britânico descobriu a penicilina?", answer: "Fleming" },
    { question: "Qual é o osso mais longo do corpo humano?", answer: "Femur" },
    { question: "Como se chama o processo pelo qual as plantas produzem seu próprio alimento usando luz?", answer: "Fotossintese" },
    { question: "Qual é a unidade básica que forma todos os seres vivos?", answer: "Celula" },
    { question: "Qual planeta é famoso por ter grandes anéis visíveis ao seu redor?", answer: "Saturno" },
    { question: "Qual gás, mais leve que o ar, é usado para encher balões que sobem?", answer: "Helio" },
    { question: "Qual cientista austríaco é considerado o pai da genética moderna?", answer: "Mendel" },
    { question: "Como se chama o processo de divisão da célula?", answer: "Mitose" },
    { question: "Qual órgão do corpo humano filtra o sangue e produz a urina?", answer: "Rim" },
    { question: "Qual gás é usado para dar a cor vermelha em letreiros luminosos?", answer: "Neonio" },
    { question: "Quantos ossos tem, em média, o corpo de um humano adulto?", answer: "206" },
    { question: "Qual cientista russo criou a tabela periódica dos elementos?", answer: "Mendeleev" },
    { question: "Como se chama a camada da atmosfera que nos protege dos raios ultravioleta do Sol?", answer: "Camada de Ozonio" },
    { question: "Qual é a estrela mais próxima da Terra?", answer: "Sol" },
    { question: "Como se chama o processo de transformação da água líquida em vapor?", answer: "Evaporacao" },
    { question: "Qual cientista britânico propôs a teoria da evolução das espécies?", answer: "Darwin" },
    { question: "Qual é o gás mais abundante na atmosfera da Terra?", answer: "Nitrogenio" },
    { question: "Como se chama a força que nos mantém presos ao chão?", answer: "Gravidade" },
  ],
  historia: [
    { question: "Em que ano o Brasil foi descoberto pelos portugueses?", answer: "1500" },
    { question: "Em que ano a Segunda Guerra Mundial terminou?", answer: "1945" },
    { question: "Quem assinou a Lei Áurea, abolindo a escravidão no Brasil?", answer: "Princesa Isabel" },
    { question: "Qual civilização antiga construiu as pirâmides do Egito?", answer: "Egipcios" },
    { question: "Em que ano o Brasil se tornou independente de Portugal?", answer: "1822" },
    { question: "Quem foi o líder da Alemanha nazista na Segunda Guerra?", answer: "Hitler" },
    { question: "Qual muro caiu em 1989, símbolo do fim da Guerra Fria?", answer: "Muro de Berlim" },
    { question: "Qual navegador português chegou ao Brasil em 1500?", answer: "Cabral" },
    { question: "Em que ano começou a Revolução Francesa?", answer: "1789" },
    { question: "Quem foi o primeiro presidente do Brasil?", answer: "Deodoro da Fonseca" },
    { question: "Qual foi o grande império antigo que tinha Roma como capital?", answer: "Imperio Romano" },
    { question: "Como se chama o período histórico entre a Idade Antiga e a Idade Moderna?", answer: "Idade Media" },
    { question: "Quem foi o primeiro imperador do Brasil, após a independência?", answer: "Dom Pedro I" },
    { question: "Em que ano começou a Primeira Guerra Mundial?", answer: "1914" },
    { question: "Qual movimento cultural e artístico floresceu na Europa nos séculos XV e XVI?", answer: "Renascimento" },
    { question: "Quem foi a famosa rainha do Egito Antigo, conhecida por sua beleza e poder?", answer: "Cleopatra" },
    { question: "Em que ano o ser humano pisou na Lua pela primeira vez?", answer: "1969" },
    { question: "Como eram chamadas as divisões de terra doadas pelo rei de Portugal no Brasil colônia?", answer: "Capitanias Hereditarias" },
    { question: "Quem foi o líder cubano ao lado de Fidel Castro na Revolução Cubana?", answer: "Che Guevara" },
    { question: "Em que ano ocorreu a Proclamação da República no Brasil?", answer: "1889" },
    { question: "Qual navio afundou em 1912 após bater num iceberg no Oceano Atlântico?", answer: "Titanic" },
    { question: "Como é chamado o período em que o Brasil foi governado por militares, de 1964 a 1985?", answer: "Ditadura Militar" },
    { question: "Em qual continente fica o Egito?", answer: "Africa" },
    { question: "Qual navegador português liderou a expedição que completou a primeira volta ao mundo?", answer: "Magalhaes" },
    { question: "Em que ano começou a Grande Depressão econômica mundial?", answer: "1929" },
    { question: "Quem foi o líder indiano que promoveu a resistência pacífica contra o domínio britânico?", answer: "Gandhi" },
    { question: "Qual foi a guerra do século XIX entre Brasil, Argentina e Uruguai contra o Paraguai?", answer: "Guerra do Paraguai" },
    { question: "Em que ano terminou a Primeira Guerra Mundial?", answer: "1918" },
    { question: "Quem foi a primeira mulher a viajar ao espaço?", answer: "Valentina Tereshkova" },
    { question: "Qual documento declarou a independência dos Estados Unidos, em 1776?", answer: "Declaracao de Independencia" },
  ],
  cinema: [
    { question: "Quem dirigiu o filme Tubarão, de 1975?", answer: "Spielberg" },
    { question: "Qual é o nome do protagonista de Star Wars, filho de Darth Vader?", answer: "Luke" },
    { question: "Qual estúdio de animação criou Toy Story?", answer: "Pixar" },
    { question: "Qual filme de 1997 conta a história do naufrágio de um navio famoso?", answer: "Titanic" },
    { question: "Qual é o nome do super-herói conhecido como Homem de Ferro?", answer: "Tony Stark" },
    { question: "Qual personagem da Disney tem os poderes de congelar tudo com as mãos?", answer: "Elsa" },
    { question: "Quem dirigiu Vingadores: Ultimato (sobrenome)?", answer: "Russo" },
    { question: "Qual filme brasileiro ganhou o Oscar de Melhor Filme Internacional em 2025?", answer: "Ainda Estou Aqui" },
    { question: "Qual é o nome do tubarão do filme clássico de 1975?", answer: "Bruce" },
    { question: "Em que cidade fica a maior parte da indústria de cinema americana?", answer: "Hollywood" },
    { question: "Qual é o sobrenome do ator que interpretou o Coringa no filme de 2019?", answer: "Phoenix" },
    { question: "Qual editora de quadrinhos é dona do Batman e do Superman?", answer: "DC Comics" },
    { question: "Qual é o nome do palhaço assustador do filme de terror 'It: A Coisa'?", answer: "Pennywise" },
    { question: "Qual é o nome do robô protagonista de uma animação da Pixar sobre limpar a Terra?", answer: "WALL-E" },
    { question: "Qual é o sobrenome do diretor mexicano do filme Gravidade?", answer: "Cuaron" },
    { question: "Qual é o nome da boneca assombrada de uma famosa série de filmes de terror?", answer: "Annabelle" },
    { question: "Qual atriz interpretou a Mulher Maravilha nos filmes recentes?", answer: "Gal Gadot" },
    { question: "Qual é o nome da cidade fictícia onde vive o Batman?", answer: "Gotham" },
    { question: "Qual é o nome do vilão leão de 'O Rei Leão'?", answer: "Scar" },
    { question: "Qual filme brasileiro de 2002 retrata o crime organizado no Rio de Janeiro?", answer: "Cidade de Deus" },
    { question: "Qual ator interpretou o personagem-título do filme Forrest Gump?", answer: "Tom Hanks" },
    { question: "Qual é o nome da nave espacial pilotada por Han Solo em Star Wars?", answer: "Millennium Falcon" },
    { question: "Qual é o sobrenome do diretor sul-coreano do filme Parasita, vencedor do Oscar em 2020?", answer: "Bong" },
    { question: "Qual vilão usa uma manopla com pedras infinitas nos filmes da Marvel?", answer: "Thanos" },
    { question: "Qual é o nome do peixinho protagonista de 'Procurando Nemo'?", answer: "Nemo" },
    { question: "Qual ator interpretou Jack no filme Titanic?", answer: "Leonardo DiCaprio" },
    { question: "Como é chamado o universo cinematográfico que reúne os heróis da Marvel?", answer: "Universo Marvel" },
    { question: "Em qual animação da Disney uma sereia deseja se tornar humana?", answer: "A Pequena Sereia" },
    { question: "Qual é o nome do detetive fictício criado por Arthur Conan Doyle, adaptado várias vezes pro cinema?", answer: "Sherlock Holmes" },
  ],
  letras: [
    { question: "Quem escreveu o livro Dom Casmurro?", answer: "Machado de Assis" },
    { question: "Qual é o autor de O Cortiço?", answer: "Aluisio Azevedo" },
    { question: "Quem escreveu as peças Romeu e Julieta?", answer: "Shakespeare" },
    { question: "Qual saga de livros conta a história de um menino bruxo?", answer: "Harry Potter" },
    { question: "Quem escreveu Grande Sertão: Veredas?", answer: "Guimaraes Rosa" },
    { question: "Quantas letras tem o alfabeto português atual?", answer: "26" },
    { question: "Quem escreveu Memórias Póstumas de Brás Cubas?", answer: "Machado de Assis" },
    { question: "Como se chama uma composição poética de 14 versos?", answer: "Soneto" },
    { question: "Quem escreveu o romance Vidas Secas?", answer: "Graciliano Ramos" },
    { question: "Qual autor português escreveu Os Lusíadas?", answer: "Camoes" },
    { question: "Quem escreveu o poema 'Canção do Exílio' ('Minha terra tem palmeiras')?", answer: "Goncalves Dias" },
    { question: "Qual é o autor do romance 'Iracema'?", answer: "Jose de Alencar" },
    { question: "Qual movimento literário brasileiro do século XIX valorizava a natureza e o nacionalismo?", answer: "Romantismo" },
    { question: "Quem escreveu o romance 'Capitães da Areia'?", answer: "Jorge Amado" },
    { question: "Qual autor britânico criou o detetive Sherlock Holmes?", answer: "Arthur Conan Doyle" },
    { question: "Como se chama o gênero literário que narra fatos em versos, geralmente com rima?", answer: "Poesia" },
    { question: "Quem escreveu 'O Pequeno Príncipe'?", answer: "Antoine de Saint-Exupery" },
    { question: "Qual é o nome do livro mais vendido do mundo, texto sagrado do cristianismo?", answer: "Biblia" },
    { question: "Quem escreveu o romance '1984', sobre vigilância e totalitarismo?", answer: "George Orwell" },
    { question: "Como se chama o evento de 1922 que marcou o início do Modernismo no Brasil?", answer: "Semana de Arte Moderna" },
    { question: "Quem escreveu o clássico 'Dom Quixote'?", answer: "Cervantes" },
    { question: "Como se chama a figura de linguagem que compara duas coisas usando a palavra 'como'?", answer: "Comparacao" },
    { question: "Quem escreveu o romance 'A Moreninha'?", answer: "Joaquim Manuel de Macedo" },
    { question: "Como se chama o gênero literário em prosa que conta histórias fictícias longas?", answer: "Romance" },
    { question: "Quem escreveu 'Cem Anos de Solidão'?", answer: "Gabriel Garcia Marquez" },
    { question: "Quem escreveu o famoso poema 'O Navio Negreiro'?", answer: "Castro Alves" },
    { question: "Como se chama o conjunto de regras que organiza a escrita correta das palavras?", answer: "Ortografia" },
    { question: "Quem escreveu o romance 'A Hora da Estrela'?", answer: "Clarice Lispector" },
    { question: "Quem escreveu 'Os Sertões', sobre a Guerra de Canudos?", answer: "Euclides da Cunha" },
  ],
};

async function main() {
  let count = 0;
  for (const [themeKey, questions] of Object.entries(QUESTIONS)) {
    for (const q of questions) {
      const exists = await prisma.quizQuestion.findFirst({
        where: { themeKey, question: q.question },
      });
      if (!exists) {
        await prisma.quizQuestion.create({ data: { themeKey, ...q } });
        count++;
      }
    }
  }
  console.log(`Seed do Quiz concluído. ${count} pergunta(s) nova(s) adicionada(s).`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
