// O TRIBUNAL — conteúdo.
//
// REGRAS DE CONTEÚDO:
//   - crime do COTIDIANO ABSURDO: algo que poderia acontecer com qualquer um
//     (nada de crime de verdade, nada ofensivo, nada de tema sensível);
//   - sem marcar gênero: o texto funciona depois de "RÉU: {nick}";
//   - a graça vem dos ARGUMENTOS dos jogadores — a acusação só dá o gancho.
//
// Etapa 3 (zip 574): lista completa — ~150 acusações e 40 sentenças.

export const ACUSACOES = [
  // casa e família
  "Comeu o último pedaço de pizza e colocou a caixa vazia de volta na geladeira.",
  "Comeu o chocolate que estava escrito NÃO COMER.",
  "Deixou só um dedo de refrigerante na garrafa e guardou na geladeira.",
  "Usou a toalha dos outros e deixou molhada em cima da cama.",
  "Deixou a louça de molho por três dias pra ela se lavar sozinha.",
  "Colocou pote de sorvete com feijão no freezer, sabendo que alguém ia se enganar.",
  "Terminou o papel higiênico e não trocou o rolo.",
  "Mexeu no controle do ar-condicionado sem consultar ninguém.",
  // internet e celular
  "Roubou o Wi-Fi do vizinho por dois anos.",
  "Fingiu que não viu a mensagem, mas apareceu online logo depois.",
  "Começou uma discussão no grupo da família e desapareceu.",
  "Mandou áudio de 7 minutos pra dizer que ia se atrasar.",
  "Deixou o celular no volume máximo numa sala de espera.",
  "Respondeu só 'kkk' numa mensagem importante.",
  "Deu spoiler do final da série no grupo de amigos.",
  "Curtiu uma foto de 2014 enquanto espiava o perfil de alguém.",
  // amigos e rolês
  "Disse que estava chegando quando ainda estava no banho.",
  "Pediu só uma batatinha e comeu metade da porção dos outros.",
  "Sumiu na hora de dividir a conta do restaurante.",
  "Marcou o rolê, confirmou presença e não apareceu.",
  "Cantou a música errada no karaokê com a maior confiança do mundo.",
  "Contou o mesmo 'segredo' pra cinco pessoas diferentes.",
  // trabalho e escola
  "Esquentou peixe no micro-ondas do escritório.",
  "Respondeu 'como mencionado anteriormente' num e-mail só pra humilhar.",
  "Colocou o nome no trabalho em grupo sem ter feito nada.",
  "Disse que a internet caiu no meio da reunião, mas só estava com preguiça.",
  // rua e vizinhança
  "Buzinou no exato segundo em que o semáforo abriu.",
  "Estacionou ocupando duas vagas no supermercado.",
  "Furou a fila da padaria fingindo que estava com alguém.",
  "Pegou o carrinho de supermercado de outra pessoa sem perceber e saiu andando.",
  // casa e família (mais)
  "Colocou a colher suja de volta na gaveta.",
  "Deixou a porta da geladeira aberta enquanto decidia o que comer.",
  "Escondeu o controle remoto e fingiu que não sabia de nada.",
  "Pegou o carregador de alguém emprestado e nunca devolveu.",
  "Usou escondido o shampoo caro de outra pessoa da casa.",
  "Guardou o pote de manteiga vazio de volta na geladeira.",
  "Comeu o recheio do biscoito e devolveu a bolacha pro pacote.",
  "Deixou uma única batata frita no prato pra não parecer que comeu tudo.",
  "Mudou a senha do Wi-Fi e não avisou ninguém.",
  "Assistiu ao próximo episódio da série sem esperar o resto da casa.",
  "Colocou roupa branca junto com a colorida na máquina de lavar.",
  "Dormiu no sofá com a TV ligada e jurou que estava assistindo.",
  "Esquentou o feijão e largou a panela na pia sem água.",
  "Tomou o último gole de café e não passou mais.",
  "Acordou a casa inteira cantando no chuveiro às 6 da manhã.",
  "Escondeu o chocolate no congelador, atrás do frango.",
  "Usou a última pilha do controle da TV pra ligar o próprio videogame.",
  "Fingiu que estava dormindo pra não lavar a louça.",
  "Colocou o despertador pra tocar 12 vezes e desligou todas.",
  "Ficou três horas escolhendo um filme e dormiu nos primeiros 10 minutos.",
  // internet e celular (mais)
  "Mandou 'bom dia' com imagem de flor brilhante em todos os grupos.",
  "Visualizou a mensagem e respondeu três dias depois com 'kkkk'.",
  "Mandou 'oi' e sumiu antes de dizer o que queria.",
  "Criou um grupo no WhatsApp e saiu logo depois.",
  "Postou a foto do grupo em que só a própria cara estava bonita.",
  "Colocou o celular no silencioso e ignorou 14 ligações da mãe.",
  "Respondeu um e-mail importante do trabalho com 'blz'.",
  "Mandou figurinha em vez de responder a pergunta.",
  "Ficou com 1% de bateria e pediu o carregador de todo mundo na festa.",
  "Marcou todos os amigos num sorteio de promoção.",
  "Respondeu uma mensagem de texto com um áudio.",
  "Mudou a foto do grupo da família sem consultar ninguém.",
  "Espalhou uma notícia falsa no grupo e depois disse 'recebi assim'.",
  "Tirou print da conversa e mandou pro grupo errado.",
  "Ouviu música tão alto no fone que o ônibus inteiro escutou.",
  "Postou foto da comida antes de deixar os outros comerem.",
  "Curtiu o próprio post.",
  "Ficou 10 minutos 'digitando…' e mandou só 'ok'.",
  "Esqueceu o aniversário do melhor amigo e mandou parabéns atrasado com um GIF.",
  // amigos e rolês (mais)
  "Pediu 'só um gole' e tomou metade do suco.",
  "Contou o final do filme na fila do cinema.",
  "Chegou na festa só na hora do bolo.",
  "Levou um saco de gelo pro churrasco e comeu a noite toda.",
  "Ficou com a última coxinha da festa sem oferecer pra ninguém.",
  "Tirou foto de todo mundo comendo e postou sem pedir.",
  "Disse 'tô a 5 minutos' estando a 40.",
  "Pegou carona e ainda reclamou da música do carro.",
  "Deu de amigo secreto o presente que tinha ganhado no ano anterior.",
  "Ficou em cima do muro na discussão e depois disse 'eu avisei'.",
  "Puxou o parabéns fora do ritmo e levou todo mundo junto.",
  "Pediu pizza de abacaxi pra mesa inteira sem perguntar.",
  "Disse 'vou só ao banheiro' e voltou 40 minutos depois.",
  "Comeu a última fatia de pizza e disse que era a primeira.",
  "Prometeu levar a sobremesa e apareceu com um pacote de bolacha.",
  "Roubou batata frita do prato de todo mundo 'só pra provar'.",
  "Chamou todo mundo pro rolê e foi o primeiro a ir embora.",
  "Mudou a playlist da festa pra tocar só as próprias músicas.",
  "Aprendeu uma dancinha da internet e dançou no almoço de família inteiro.",
  "Comprou ingresso pro show e dormiu na hora de sair de casa.",
  // trabalho e escola (mais)
  "Respondeu 'pode ser' a uma pergunta de sim ou não na reunião.",
  "Deixou a câmera desligada na reunião e dormiu.",
  "Comeu o iogurte da geladeira do escritório que tinha o nome de outra pessoa.",
  "Marcou uma 'reunião rápida' e falou por duas horas.",
  "Pegou uma caneta emprestada e levou pra casa.",
  "Esqueceu o microfone aberto e cantou no meio da reunião.",
  "Copiou a lição e tirou nota maior que quem emprestou.",
  "Marcou reunião pra sexta-feira às 17h.",
  "Imprimiu 80 páginas coloridas na impressora do trabalho.",
  "Clicou em 'responder a todos' num e-mail pra empresa inteira.",
  "Entrou 30 minutos depois do início da aula com um café na mão.",
  "Levou marmita de ovo cozido pro escritório.",
  "Fingiu resolver algo importante no computador enquanto jogava paciência.",
  "Disse que estava 'quase terminando' um trabalho que nem tinha começado.",
  // rua, vizinhança e transporte (mais)
  "Parou no meio da calçada pra olhar o celular.",
  "Sentou na janela do ônibus e colocou a bolsa no banco do corredor.",
  "Tirou o sapato no meio do voo.",
  "Reclinou a poltrona do avião até o colo de quem estava atrás.",
  "Fez barulho de obra no apartamento às 8 da manhã de domingo.",
  "Deixou o cachorro latir a noite inteira e disse que ele nunca late.",
  "Pegou o elevador pra subir um andar só.",
  "Fez o motorista do aplicativo esperar 15 minutos.",
  "Sentou no banco preferencial e fingiu que estava dormindo.",
  "Cumprimentou um estranho achando que era um conhecido e continuou a conversa.",
  "Comeu o pão no caminho da padaria e chegou em casa com meio pão.",
  "Tocou a campainha do vizinho e saiu correndo — com 30 anos de idade.",
  "Foi ao mercado comprar pão e voltou com R$ 200 de besteira.",
  // comida (mais)
  "Colocou ketchup na pizza.",
  "Esquentou o almoço no micro-ondas e esqueceu lá dentro.",
  "Comeu todo o recheio da lasanha e deixou só a massa.",
  "Pediu delivery e escondeu a embalagem pra ninguém pedir um pedaço.",
  "Tomou refrigerante direto no gargalo da garrafa da família.",
  "Comeu o bolo de aniversário antes de cantarem parabéns.",
  "Colocou uva-passa no arroz de Natal.",
  "Fez churrasco e só serviu linguiça queimada.",
  "Pediu 'só uma mordida' do lanche e comeu metade.",
  "Tirou todo o cheiro-verde da comida e ainda reclamou do prato.",
  "Fez brigadeiro de panela e comeu tudo antes de chegar a visita.",
  "Colocou açúcar no macarrão achando que era sal.",
  "Guardou o refrigerante aberto na geladeira sem tampa.",
  "Comeu a sobremesa de outra pessoa achando que ninguém ia perceber.",
  "Cortou o bolo pelo meio e deixou as bordas pros outros.",
  "Disse que sabia cozinhar e queimou a água do macarrão.",
  "Falou que ia pra academia e foi comer pastel.",
  // variados
  "Guardou o controle do ar-condicionado no bolso pra ninguém mexer.",
  "Deixou papel de bala escondido entre as almofadas do sofá.",
  "Levou o guarda-chuva de outra pessoa num dia de chuva.",
  "Assistiu vídeo sem fone na sala de espera do médico.",
  "Contou a mesma piada pela décima vez no mesmo almoço.",
  "Mandou 'me liga' e não atendeu quando ligaram.",
  "Devolveu o carro emprestado sem uma gota de gasolina.",
  "Tirou foto do prato no restaurante com flash.",
  "Pediu o prato mais caro e depois sugeriu dividir a conta igualmente.",
  "Ficou com o troco do pão que era do irmão.",
  "Desligou o videogame no meio da partida de outra pessoa.",
  "Reservou quatro cadeiras na piscina com toalhas e não apareceu.",
  "Esqueceu a câmera ligada depois de dar tchau na chamada de vídeo.",
  "Dormiu com a TV no volume 60.",
  "Salvou o contato de um amigo no celular como 'Não atender'.",
  "Usa a senha do streaming de todo mundo e nunca pagou nenhum.",
  "Colocou música no alarme às 5 da manhã e dormiu de novo.",
  // dilemas e defesas possíveis — feitos pra dividir o júri (zip 583)
  "Cortou um pedaço do bolo antes da festa e disfarçou o buraco com cobertura.",
  "Contou pra todo mundo um segredo, mas jura que 'não era segredo de verdade'.",
  "Devolveu o dinheiro emprestado, só que R$ 2 a menos, dizendo que era 'a taxa'.",
  "Chegou tarde e culpou o trânsito, mas o vizinho viu a pessoa saindo em cima da hora.",
  "Terminou o trabalho em cima da hora e ainda reclamou que ninguém ajudou.",
  "Pegou a última fatia perguntando 'alguém quer?' com a boca já cheia.",
  "Marcou o rolê, escolheu o lugar, e foi o único que não apareceu.",
  "Deu palpite na receita da avó e depois disse que 'só estava ajudando'.",
  "Emprestou pra alguém um livro que era de outra pessoa e nunca avisou o dono.",
  "Prometeu guardar segredo e contou 'só pra uma pessoa', que contou pra todas.",
  "Comeu a marmita da geladeira jurando que a etiqueta com o nome 'caiu sozinha'.",
  "Furou a fila jurando que estava só 'perguntando uma coisa' pro atendente.",
  "Usou o carregador dos outros dizendo que 'o meu ia estragar mesmo'.",
  "Não respondeu a mensagem porque 'ia responder pessoalmente, era mais educado'.",
  "Bebeu o refrigerante marcado com nome jurando que 'a letra estava apagada'.",
  "Sentou no lugar marcado dizendo que 'não tinha nome, tinha só uma jaqueta'.",
  "Pegou o guarda-chuva errado porque 'era idêntico ao meu, juro'.",
  "Cancelou em cima da hora porque 'surgiu algo mais importante', sem dizer o quê.",
  "Comeu a sobremesa do colega alegando que 'tinham dito que talvez ninguém fosse querer'.",
  "Estacionou na vaga do vizinho alegando que 'aquela vaga vive vazia mesmo'.",
  "Confessou que fura sinal vermelho de madrugada 'quando não tem ninguém'.",
  "Admitiu que aumenta a própria história de pescaria toda vez que conta.",
  "Contou que finge estar sem sinal pra sair de reunião chata.",
  "Disse que devolve roupa depois de usar uma vez, com a etiqueta escondida.",
  "Assumiu que come em pé, direto da geladeira, achando que 'não conta'.",
  "Confessou que guarda os potinhos de plástico da margarina e nunca usa.",
  "Admitiu que já mandou 'kkk' sem ter achado a menor graça.",
  "Disse que finge que já sabia da notícia pra não parecer por fora.",
  "Confessou que fala 'já vou' e continua deitado por mais meia hora.",
  "Assumiu que reaproveita o mesmo 'feliz aniversário' copiado e colado todo ano.",
  "Deixou o portão aberto e o cachorro do vizinho organizou a fuga de mais três.",
  "Mexeu no termostato do escritório e começou uma guerra que durou o inverno todo.",
  "Contou uma fofoca no grupo errado e a festa surpresa deixou de ser surpresa.",
  "Trocou o açúcar pelo sal na cozinha compartilhada 'de brincadeira' e ninguém achou graça.",
  "Deu like sem querer numa foto de 2015 e teve que explicar por uma semana.",
  "Respondeu 'ok' num convite e a pessoa achou que era desprezo por um mês.",
  "Apagou sem querer o grupo da família e ninguém conseguiu recriar igual.",
  "Comeu o ingrediente que faltava pra receita e o jantar inteiro atrasou duas horas.",
  "Colocou a roupa no varal errado e o vizinho usou a camiseta por engano.",
  "Esqueceu de tirar o bolo do forno e a casa toda cheirou a carvão por dias.",
  "Deixa a louça 'de molho' há tanto tempo que criou vida própria.",
  "Fala no telefone no viva-voz no meio do transporte lotado.",
  "Manda áudio acelerado achando que economiza o tempo dos outros.",
  "Responde pergunta objetiva com 'depende' e não explica de quê.",
  "Guarda comida estragada na geladeira 'pra decidir depois'.",
  "Deixa o carrinho do supermercado atravessado no corredor e some.",
  "Empurra a porta que está escrito PUXE e culpa a porta.",
  "Fura a dieta e conta pra todo mundo que 'começa segunda de novo'.",
  "Chega no cinema com o filme começado e pergunta o que já aconteceu.",
  "Pega o controle e assiste 40 minutos de vídeos curtos sem escolher nada.",
  "Responde e-mail com 'seguindo o fio' pra parecer ocupado.",
  "Entra na chamada, fala 'concordo com o que foi dito' e sai.",
  "Promete revisar o documento e só muda a cor de um título.",
  "Marca todo mundo como urgente e depois some por três dias.",
  "Aceita a tarefa na reunião e finge que esqueceu na hora de entregar.",
  "Usa 'a gente se fala' pra encerrar toda conversa e nunca fala.",
  "Coloca abacaxi na pizza e ainda oferece pros outros com orgulho.",
  "Come o miolo do pão e devolve as cascas pro pacote.",
  "Serve o próprio prato primeiro e sempre o mais cheio.",
  "Deixa um dedo de suco na garrafa 'pra não ter que lavar agora'.",
  "Diz que 'não tá com fome' e depois belisca a comida de todo mundo.",
  // lote grande (zip 584): dia a dia, absurdos e "gravíssimos" bobos
  "Comeu o chocolate de outra pessoa e colocou a embalagem de volta no armário.",
  "Trocou o açúcar pelo sal e ficou esperando alguém tomar café.",
  "Fingiu que não viu a mensagem para não precisar responder.",
  "Terminou o papel higiênico e deixou o rolo vazio no lugar.",
  "Abriu a geladeira cinco vezes esperando que aparecesse comida nova.",
  "Comeu a comida etiquetada com o nome de outra pessoa.",
  "Roubou a coberta durante a noite e deixou outra pessoa congelando.",
  "Apertou o botão do elevador e depois apertou todos os outros andares.",
  "Ouviu um áudio de 4 minutos e respondeu apenas \"kkkk\".",
  "Visualizou a mensagem e demorou três dias para responder.",
  "Colocou \"kkkkkkkk\" sem ter achado graça.",
  "Pegou o último lugar na fila fingindo que estava ali desde o começo.",
  "Entrou no banho e percebeu que não havia toalha, mas decidiu continuar mesmo assim.",
  "Desligou o Wi-Fi para economizar energia enquanto todos estavam jogando.",
  "Comeu a batata frita de outra pessoa dizendo que \"só ia pegar uma\".",
  "Disse \"não estou com fome\" e depois comeu metade da comida do amigo.",
  "Roubou o lugar de estacionamento de alguém que estava com a seta ligada.",
  "Fingiu estar dormindo para não lavar a louça.",
  "Colocou a louça suja na pia e declarou que \"já tinha feito sua parte\".",
  "Deixou apenas uma gota de suco na garrafa para não precisar encher novamente.",
  "Pegou o controle remoto e se recusou a dizer onde colocou.",
  "Mudou a senha do Wi-Fi e não contou para ninguém.",
  "Usou o banheiro e saiu sem perceber que deixou a luz acesa.",
  "Comeu o último biscoito e culpou o cachorro.",
  "Colocou uma música horrível no carro e se recusou a trocar.",
  "Falou \"essa é minha última partida\" e jogou mais duas horas.",
  "Roubou a sombra de um cidadão durante uma caminhada.",
  "Ensinou uma barata a reconhecer seu próprio nome.",
  "Foi flagrado conversando sozinho e mudou de assunto quando perguntaram.",
  "Roubou uma cadeira e devolveu uma mesa.",
  "Entrou em uma padaria apenas para perguntar as horas.",
  "Passou três horas procurando os óculos enquanto eles estavam na própria cabeça.",
  "Acusou o gato de ter cometido um crime que claramente foi cometido pelo cachorro.",
  "Abriu um pacote de biscoitos pelo lado errado de propósito.",
  "Adiantou o despertador cinco minutos só pra ter o prazer de desligá-lo antes.",
  "Entrou no elevador, apertou o andar errado e decidiu aceitar seu destino.",
  "Colocou ketchup em uma comida que claramente não precisava de ketchup.",
  "Comprou uma planta e esqueceu que plantas precisam de água.",
  "Ficou olhando para o micro-ondas esperando o último segundo terminar.",
  "Disse \"já vou dormir\" e ficou mais duas horas olhando vídeos.",
  "Abriu um pacote de salgadinho fazendo barulho durante uma reunião.",
  "Fingiu que estava procurando alguma coisa na geladeira para evitar uma conversa.",
  "Mandou \"kkkk\" em uma conversa na qual absolutamente nada era engraçado.",
  "Fingiu que não conhecia uma pessoa para evitar cumprimentá-la.",
  "Colocou o despertador para 7h e levantou às 11h.",
  "Entrou em uma sala e esqueceu imediatamente por que entrou.",
  "Sequestrou o boneco de neve de uma criança.",
  "Roubou três meias e deixou apenas as que não formavam pares.",
  "Abriu um guarda-chuva dentro de casa para testar se funcionava.",
  "Tentou subornar um pombo com uma migalha de pão.",
  "Declarou guerra ao próprio despertador.",
  "Perseguiu uma borboleta por 20 minutos e perdeu.",
  "Tentou negociar com uma porta automática.",
  "Chamou o cachorro pelo nome do irmão durante cinco anos.",
  "Entrou em uma loja apenas para usar o ar-condicionado.",
  "Ficou esperando o elevador chegar enquanto estava no andar errado.",
  "Tentou assustar um gato e acabou sendo assustado.",
  "Colocou uma banana na geladeira e defendeu sua decisão perante testemunhas.",
  "Passou uma semana tentando descobrir quem estava roubando suas meias.",
  "Deu nome para uma barata e fez luto de três dias quando a barata morreu.",
  "Tentou convencer o GPS de que a rua certa era outra.",
  "Pediu desculpas para uma cadeira depois de bater o pé nela.",
  "Discutiu com uma máquina de autoatendimento.",
  "Ficou irritado porque o próprio reflexo no espelho copiava cada movimento.",
  "Tentou pegar uma mosca com um copo durante 40 minutos.",
  "Acusou o vento de bagunçar seu cabelo de propósito.",
  "Faltou a um compromisso alegando gripe e postou fotos na praia no mesmo dia.",
  "Prometeu devolver R$ 10 e devolveu R$ 9,99.",
  "Disse \"não vou comer sobremesa\" e depois comeu a sobremesa de todos.",
  "Descobriu a senha do Wi-Fi e se recusou a compartilhar.",
  "Pegou o último pedaço de pizza e perguntou \"alguém quer?\"",
  "Mandou uma mensagem reclamando de alguém... para a própria pessoa.",
  "Tentou sair de uma conversa fingindo que perdeu o sinal.",
  "Fingiu que não ouviu alguém chamando seu nome.",
  "Disse \"vou chegar em cinco minutos\" sabendo que demoraria uma hora.",
  "Roubou a última batata frita depois de perguntar \"ninguém quer?\"",
  "Pôs o celular pra carregar e reclamou que a bateria travou nos 99%.",
  "Contou uma história obviamente falsa e insistiu nela mesmo desmentido.",
  "Falou \"não estou com sono\" e dormiu em 30 segundos.",
  "Reclamou o filme inteiro porque o vizinho de poltrona respirava alto.",
  "Começou uma discussão na internet citando uma fonte inventada na hora.",
  "Deixou 2 segundos restantes no micro-ondas e foi embora.",
  "Abriu a geladeira, olhou tudo e fechou sem pegar nada.",
  "Colocou o rolo de papel higiênico ao contrário.",
  "Mandou um áudio de 6 minutos para dizer uma coisa que poderia ser escrita em \"ok\".",
  "Respondeu \"você que sabe\" esperando que adivinhassem o que queria.",
  "Disse \"não precisa trazer nada\" e depois ficou esperando que trouxessem alguma coisa.",
  "Respondeu \"depois eu vejo\" e nunca mais viu.",
  "Perguntou \"quem está falando?\" para alguém que tinha acabado de ligar.",
  "Deixou uma colher dentro da pia e declarou que a louça estava lavada.",
  "Pegou o celular pra ver as horas e, 40 minutos depois, via vídeos de restauração de vasos.",
  "Abriu o presente com cuidado e guardou o papel amassado pra \"usar outra hora\".",
  "Ficou preso numa ligação porque ninguém queria ser o primeiro a desligar.",
  "Disse \"só vou descansar cinco minutinhos\" e acordou no dia seguinte.",
  "Colocou algo em um lugar \"para não esquecer\" e imediatamente esqueceu onde colocou.",
  "Comeu o último pedaço de pizza, mas deixou a borda.",
];

// Sentenças do veredito (só quando o réu é CONDENADO).
export const SENTENCAS = [
  "lavar a louça de todo mundo por um mês",
  "pagar a próxima pizza sozinho",
  "ouvir só música de elevador por uma semana",
  "responder toda mensagem do grupo da família em até 1 minuto",
  "usar meia com chinelo em público por três dias",
  "ficar uma semana sem Wi-Fi",
  "pedir desculpas ao vivo no grupo da família",
  "carregar o celular de todo mundo na próxima viagem",
  "comer só pão sem manteiga por uma semana",
  "assistir ao filme mais longo do mundo sem poder pegar o celular",
  "chegar 15 minutos adiantado em todos os compromissos do mês",
  "trocar o toque do celular por um pato grasnando",
  "limpar a geladeira do escritório",
  "escutar todos os áudios do grupo em velocidade normal",
  "segurar a porta do elevador pra todo mundo por um mês",
  "levar bolo pra todo mundo na segunda-feira",
  "deixar a última fatia de pizza pros outros até o fim do ano",
  "cantar parabéns sozinho em todos os aniversários do mês",
  "passar um dia inteiro sem reclamar de nada",
  "tirar o lixo de casa por duas semanas",
  "segurar o guarda-chuva do vizinho num dia de sol",
  "ouvir inteiro, sem acelerar, o áudio de 7 minutos da tia",
  "ser o motorista da turma pelo resto do ano",
  "pedir 'por favor' ao micro-ondas antes de usar",
  "levar todos os amigos pra tomar sorvete",
  "trocar a foto de perfil pela foto do RG por uma semana",
  "organizar o próximo churrasco sozinho",
  "usar uma camiseta escrita 'SOU CULPADO' por um dia inteiro",
  "apresentar 10 minutos de slides explicando onde errou",
  "ficar sem sobremesa por duas semanas",
  "devolver tudo o que pegou emprestado desde 2019",
  "escrever uma carta de desculpas à mão",
  "assistir à novela das nove com a avó sem mexer no celular",
  "pagar o café de todo mundo por uma semana",
  "dar bom dia pra todo mundo no elevador por um mês",
  "entregar o controle da TV pros outros por um mês",
  "cantar uma música de desculpas no próximo karaokê",
  "responder 'bom dia' no grupo da família todos os dias do mês",
  "lavar a garrafa de todo mundo depois do futebol",
  "fazer uma dancinha pedindo perdão no grupo da família",
];

// Argumentos genéricos dos BOTS de teste (servem pra qualquer acusação).
export const ARGUMENTOS_BOT = {
  promotor: [
    "Excelência, as provas são claras: havia testemunhas e migalhas por todo lado.",
    "O réu já tinha feito isso antes. Isso não é um acidente, é um hábito.",
    "Senhoras e senhores do júri, olhem nos olhos do réu. Isso é culpa pura.",
    "Encontramos digitais do réu na cena do crime. Não há o que discutir.",
    "O réu tentou apagar as provas, e isso diz tudo.",
  ],
  advogado: [
    "Excelência, meu cliente estava dormindo na hora do crime.",
    "Isso foi uma armação! Meu cliente é a verdadeira vítima aqui.",
    "Quem nunca fez isso que atire a primeira pedra.",
    "Não há nenhuma prova concreta. Só fofoca.",
    "Meu cliente só estava tentando ajudar, e agora é julgado por isso.",
  ],
  acusado: [
    "Excelência, eu faria tudo de novo.",
    "Eu nem estava lá. Eu acho.",
    "Foi mais forte do que eu.",
    "Isso é perseguição!",
    "Eu exijo um novo advogado.",
  ],
  testemunha: [
    "Eu vi tudo com meus próprios olhos, de uma distância razoável.",
    "Posso confirmar que algo aconteceu, mas os detalhes já não lembro bem.",
    "Excelência, eu só sei o que me contaram, mas confio na fonte.",
    "Estava exatamente ali quando tudo aconteceu, ou logo depois.",
    "Não quero me comprometer, mas também não posso negar.",
  ],
};


// PACOTES: material extra pra alguns crimes (zip 585) — testemunha, prova e
// álibi do acusado. Opcional: crime sem pacote funciona normal, só com o
// texto do crime. A chave é o texto EXATO do crime em ACUSACOES.
//   testemunha — discurso direto, com um detalhe específico e estranho;
//   prova      — uma linha curta (objeto ou fato), não uma frase corrida;
//   alibi      — discurso direto do acusado, plausível o bastante pra render
//                defesa de verdade (o advogado — ou o próprio réu, em causa
//                própria — pode usar isso como ponto de partida).
export const PACOTES = {
  "Comeu o último pedaço de pizza e colocou a caixa vazia de volta na geladeira.": { testemunha: "Eu vi o acusado olhando pra pizza por uns 17 segundos antes de agir.", prova: "Uma caixa de pizza vazia, ainda morna, escondida atrás do leite.", alibi: "Eu achei que era uma pizza comunitária." },
  "Comeu o chocolate que estava escrito NÃO COMER.": { testemunha: "Ouvi um barulho de papel de chocolate às 23h. Só podia ser o acusado.", prova: "A embalagem, dobrada com cuidado demais pra parecer inocente.", alibi: "Eu pensei que NÃO COMER era o nome da marca do chocolate." },
  "Deixou só um dedo de refrigerante na garrafa e guardou na geladeira.": { testemunha: "A garrafa fazia barulho de vazia toda vez que alguém abria a geladeira.", prova: "Uma garrafa de 2 litros com exatos 3 centímetros de líquido.", alibi: "Eu tava guardando pra comemorar alguma coisa boa acontecer." },
  "Roubou o Wi-Fi do vizinho por dois anos.": { testemunha: "O sinal do vizinho sempre caía quando o acusado ligava o computador.", prova: "Um histórico de conexão com o nome da rede 'NaoEUsaSenha123'.", alibi: "Eu achei que Wi-Fi de graça era um direito humano básico." },
  "Começou uma discussão no grupo da família e desapareceu.": { testemunha: "Vi o 'digitando…' aparecer, sumir, e nunca mais uma palavra.", prova: "Um print com 47 mensagens de resposta e zero do acusado.", alibi: "Meu celular caiu na privada logo depois que mandei a mensagem." },
  "Mandou áudio de 7 minutos pra dizer que ia se atrasar.": { testemunha: "Contei no relógio: 6 minutos e 40 segundos só de introdução.", prova: "A transcrição do áudio, com 'tipo assim' contado 22 vezes.", alibi: "Eu tenho muita dificuldade em resumir as coisas, é um dom." },
  "Disse que estava chegando quando ainda estava no banho.": { testemunha: "Ouvi o chuveiro ligado no fundo da ligação, bem claramente.", prova: "Uma mensagem de voz com eco de azulejo.", alibi: "Eu já tinha decidido mentalmente que estava chegando." },
  "Contou o mesmo 'segredo' pra cinco pessoas diferentes.": { testemunha: "As cinco pessoas me procuraram no mesmo dia com a mesma novidade.", prova: "Cinco conversas privadas, cada uma achando que era a única sabendo.", alibi: "Segredo compartilhado com moderação é praticamente domínio público." },
  "Buzinou no exato segundo em que o semáforo abriu.": { testemunha: "O sinal ainda estava mudando de cor quando a buzina já tocava.", prova: "Uma gravação de câmera mostrando 0,4 segundos de diferença.", alibi: "Eu simplesmente tenho reflexos muito bons." },
  "Escondeu o controle remoto e fingiu que não sabia de nada.": { testemunha: "Vi o acusado sentar em cima de algo e depois recusar se levantar.", prova: "O controle, achado embaixo da própria almofada do acusado.", alibi: "Eu estava só esquentando o controle com o calor do meu corpo." },
  "Pegou o carregador de alguém emprestado e nunca devolveu.": { testemunha: "O carregador branco virou preto de tanto ficar na mochila do acusado.", prova: "Um cabo com fita adesiva escrito o nome de outra pessoa.", alibi: "Achei que carregador, depois de um tempo, vira propriedade de quem usa mais." },
  "Mudou a senha do Wi-Fi e não avisou ninguém.": { testemunha: "Toda a casa ficou sem internet, menos o quarto do acusado.", prova: "Um roteador com a nova senha anotada só no celular do acusado.", alibi: "Eu troquei achando que ia lembrar de avisar depois." },
  "Colocou o despertador pra tocar 12 vezes e desligou todas.": { testemunha: "Contei as batidas do despertador: exatamente 12, uma por soneca.", prova: "Um histórico de alarme com 12 horários entre 6h e 6h58.", alibi: "Eu preciso de um aquecimento gradual pra acordar direito." },
  "Mandou 'bom dia' com imagem de flor brilhante em todos os grupos.": { testemunha: "Recebi a mesma flor brilhante em quatro grupos diferentes, no mesmo minuto.", prova: "Uma imagem de flor salva desde 2019, usada todo santo dia.", alibi: "Espalhar bom humor de manhã é praticamente um serviço público." },
  "Visualizou a mensagem e demorou três dias para responder.": { testemunha: "O relógio azul apareceu na hora. A resposta, só 72 horas depois.", prova: "Um print com o horário exato da visualização e da resposta.", alibi: "Eu queria formular uma resposta à altura da pergunta." },
  "Ficou com a última coxinha da festa sem oferecer pra ninguém.": { testemunha: "Vi o acusado comer de costas pra mesa, olhando pros lados.", prova: "Farelo de coxinha no colarinho da camisa do acusado.", alibi: "Eu ofereci mentalmente, com muito carinho, pra todo mundo." },
  "Disse 'tô a 5 minutos' estando a 40.": { testemunha: "O acusado ainda estava no chinelo quando mandou essa mensagem.", prova: "Um histórico de localização mostrando 38 km de distância.", alibi: "Cinco minutos é uma unidade de tempo mais espiritual do que literal." },
  "Deu de amigo secreto o presente que tinha ganhado no ano anterior.": { testemunha: "Reconheci o papel de embrulho: era o mesmo do ano passado, reaproveitado.", prova: "Um cartão de 'Feliz Natal' de dois anos atrás, esquecido dentro da caixa.", alibi: "Eu considero isso reciclagem de afeto, não reaproveitamento." },
  "Pediu pizza de abacaxi pra mesa inteira sem perguntar.": { testemunha: "Ouvi o acusado dizer 'todo mundo vai gostar' sem perguntar a ninguém.", prova: "O pedido, no nome do acusado, sem nenhum outro sabor na mesa.", alibi: "Pizza de abacaxi é consenso universal, eu só assumi isso." },
  "Comeu a última fatia de pizza e disse que era a primeira.": { testemunha: "Só sobrava uma fatia quando cheguei, e o acusado já mastigava.", prova: "A caixa de pizza com uma única marca de dedo, no molho.", alibi: "Eu conto fatias de trás pra frente, então tecnicamente era a primeira." },
  "Deixou a câmera desligada na reunião e dormiu.": { testemunha: "O microfone captou um ronco muito característico durante a pauta.", prova: "Uma gravação da reunião com 4 minutos de silêncio suspeito.", alibi: "Eu estava concentrado de olhos fechados, é uma técnica." },
  "Comeu o iogurte da geladeira do escritório que tinha o nome de outra pessoa.": { testemunha: "Vi o pote no lixo, ainda com o nome escrito bem legível.", prova: "Um potinho vazio de iogurte de morango na lixeira do acusado.", alibi: "Eu achei que era um apelido carinhoso, não um nome de verdade." },
  "Clicou em 'responder a todos' num e-mail pra empresa inteira.": { testemunha: "Recebi o e-mail junto com as outras 214 pessoas da empresa.", prova: "Um e-mail com 'Re: Re: Re:' e a frase 'só eu que vou almoçar?'.", alibi: "Eu não sabia que 'todos' incluía todo mundo mesmo." },
  "Reclinou a poltrona do avião até o colo de quem estava atrás.": { testemunha: "Ouvi um 'ai' vindo de trás na hora exata da reclinada.", prova: "Uma poltrona travada no ângulo máximo permitido pelo fabricante.", alibi: "Eu tenho um problema de coluna que só reclina resolve." },
  "Deixou o cachorro latir a noite inteira e disse que ele nunca late.": { testemunha: "Ouvi o latido pela janela até as 3 da manhã, sem parar.", prova: "Um vídeo de 40 segundos do cachorro latindo, gravado pelo vizinho.", alibi: "Meu cachorro só late em outra dimensão, essa era outra pessoa." },
  "Tocou a campainha do vizinho e saiu correndo — com 30 anos de idade.": { testemunha: "Vi o acusado apertando a campainha e disparando pela rua.", prova: "Uma câmera de segurança com o flagrante completo, em alta definição.", alibi: "Eu estava testando se a campainha funcionava, por curiosidade científica." },
  "Colocou ketchup na pizza.": { testemunha: "Vi o acusado abrir o ketchup no meio do jantar italiano.", prova: "Uma pizza com listras vermelhas nada convencionais.", alibi: "Eu considero ketchup um tempero universal, sem exceções." },
  "Comeu o bolo de aniversário antes de cantarem parabéns.": { testemunha: "O bolo já tinha um pedaço faltando quando as velas foram acesas.", prova: "Um garfo largado do lado do bolo, ainda com massa grudada.", alibi: "Eu só estava conferindo se estava no ponto, por zelo profissional." },
  "Colocou uva-passa no arroz de Natal.": { testemunha: "Vi o pacote de uva-passa aberto do lado da panela de arroz.", prova: "Um arroz com pontinhos pretos suspeitos, nunca antes vistos na família.", alibi: "Uva-passa no arroz é tradição em algum lugar do mundo, com certeza." },
  "Comeu a sobremesa de outra pessoa achando que ninguém ia perceber.": { testemunha: "Vi o acusado trocando de prato discretamente embaixo da mesa.", prova: "Um pudim pela metade num prato que não era o do acusado.", alibi: "Eu achei que sobremesa era por conta da casa, tipo bufê." },
  "Guardou o refrigerante aberto na geladeira sem tampa.": { testemunha: "Todo o refrigerante da geladeira ficou com gosto de geladeira.", prova: "Uma garrafa de 2 litros murcha, chocha, sem gás nenhum.", alibi: "Tampa é só um item decorativo, o refrigerante respira melhor assim." },
  "Furou a fila da padaria fingindo que estava com alguém.": { testemunha: "Vi o acusado apontar pra alguém aleatório na fila e dizer que estava junto.", prova: "Um recibo de padaria com o horário 2 minutos antes de chegar.", alibi: "Eu realmente achei que conhecia aquela pessoa, foi um mal-entendido." },
  "Estacionou ocupando duas vagas no supermercado.": { testemunha: "O carro estava perfeitamente no meio das duas linhas amarelas.", prova: "Uma foto do carro, com régua improvisada mostrando os dois espaços.", alibi: "Eu tenho muito medo de risquinho, então dou uma margem de segurança." },
  "Pegou o carrinho de supermercado de outra pessoa sem perceber e saiu andando.": { testemunha: "Vi o acusado andando com o carrinho errado, cheio de itens estranhos.", prova: "Um carrinho com fraldas e ração de gato, sem nada a ver com o acusado.", alibi: "Todos os carrinhos são iguais, é uma falha de design da loja." },
  "Escondeu o chocolate no congelador, atrás do frango.": { testemunha: "Vi um vulto abrindo o congelador de fininho, tarde da noite.", prova: "Uma barra de chocolate gelada, escondida atrás de um pacote de frango.", alibi: "Chocolate gelado é uma sobremesa nova que eu tava desenvolvendo." },
  "Usou a última pilha do controle da TV pra ligar o próprio videogame.": { testemunha: "O controle da TV parou de funcionar bem na hora do jogo do acusado.", prova: "Um controle de TV vazio, do lado de um videogame ligado.", alibi: "Pilhas circulam livremente pela casa, é lei da física doméstica." },
  "Mudou a foto do grupo da família sem consultar ninguém.": { testemunha: "Recebi uma notificação de 'foto do grupo alterada' sem votação nenhuma.", prova: "A foto nova, tirada de um ângulo que só favorecia o acusado.", alibi: "Eu achei que estava desatualizada e tomei uma decisão executiva." },
  "Tirou print da conversa e mandou pro grupo errado.": { testemunha: "O print apareceu num grupo que não tinha nada a ver com o assunto.", prova: "Uma captura de tela com o nome do grupo errado bem visível.", alibi: "Os grupos têm nomes parecidos, é um problema de interface." },
  "Marcou uma 'reunião rápida' e falou por duas horas.": { testemunha: "Entrei na reunião às 14h. Saí às 16h. O assunto era sobre o cardápio do RH.", prova: "Um convite de calendário dizendo '15 minutos', sem nenhuma relação com a realidade.", alibi: "Eu só queria garantir que todo mundo entendesse bem o contexto." },
  "Pegou uma caneta emprestada e levou pra casa.": { testemunha: "Vi a caneta do escritório dentro da bolsa pessoal do acusado.", prova: "Uma caneta com o logo da empresa, longe da empresa.", alibi: "Canetas migram naturalmente entre bolsos, eu só as deixei seguir o destino." },
  "Comprou ingresso pro show e dormiu na hora de sair de casa.": { testemunha: "Mandei mensagem avisando que o show ia começar. Recebi um 'zzz' de resposta.", prova: "Um ingresso intacto, ainda dentro do envelope, na mesa de cabeceira.", alibi: "Eu decidi descansar os olhos rapidinho antes de sair." },
  "Levou marmita de ovo cozido pro escritório.": { testemunha: "O elevador inteiro sentiu o cheiro antes mesmo de chegar no andar.", prova: "Uma marmiteira com três ovos cozidos, sem nenhuma discrição.", alibi: "Proteína é proteína, o cheiro é só um efeito colateral menor." },
  "Fez o motorista do aplicativo esperar 15 minutos.": { testemunha: "O carro ficou parado na porta com o pisca-alerta ligado por 15 minutos.", prova: "Um histórico de corrida com '15 min de espera' registrado no app.", alibi: "Eu só precisava terminar de assistir o final de um episódio." },
  "Sentou no banco preferencial e fingiu que estava dormindo.": { testemunha: "Vi o acusado abrir um olho só pra checar quem estava de pé.", prova: "Um celular ainda vibrando no bolso do 'adormecido'.", alibi: "Eu tenho sono muito leve e episódios súbitos de cochilo." },
  "Foi ao mercado comprar pão e voltou com R$ 200 de besteira.": { testemunha: "O acusado voltou com quatro sacolas e nenhum pão dentro delas.", prova: "Uma nota fiscal de R$ 200 sem um único item chamado 'pão'.", alibi: "O mercado tem uma iluminação muito convidativa, não é culpa minha." },
  "Roubou o lugar de estacionamento de alguém que estava com a seta ligada.": { testemunha: "Vi a seta ligada por dois minutos antes de outro carro roubar a vaga.", prova: "Uma foto de dois carros disputando a mesma vaga, ao mesmo tempo.", alibi: "Seta ligada não é reserva de vaga, é só um enfeite do carro." },
  "Colocou a colher suja de volta na gaveta.": { testemunha: "Peguei a colher pra comer iogurte e ela já veio com sabor de ontem.", prova: "Uma colher com resíduo seco de molho de tomate, na gaveta dos talheres limpos.", alibi: "Eu achei que tinha passado uma água nela, no calor da pressa." },
  "Deixou a porta da geladeira aberta enquanto decidia o que comer.": { testemunha: "A conta de luz veio mais alta no mês em que o acusado se mudou pra cá.", prova: "Uma geladeira suada por fora, de tanto ficar aberta.", alibi: "Eu preciso ver todas as opções antes de decidir qualquer coisa da vida." },
  "Assistiu ao próximo episódio da série sem esperar o resto da casa.": { testemunha: "Vi o contador de 'episódios assistidos' avançar sozinho durante a noite.", prova: "Um histórico de streaming com o episódio marcado como visto às 2h da manhã.", alibi: "Eu só queria conferir se valia a pena continuar assistindo." },
  "Ficou três horas escolhendo um filme e dormiu nos primeiros 10 minutos.": { testemunha: "Rolamos o catálogo inteiro do streaming duas vezes antes de escolher.", prova: "Um controle remoto ainda quente, do lado de alguém roncando.", alibi: "Eu escolho com o coração, e o coração demora pra decidir." },
  "Postou a foto do grupo em que só a própria cara estava bonita.": { testemunha: "Recebi a mesma foto em que todo mundo pediu pra apagar, menos o acusado.", prova: "Uma foto com quatro pessoas de olho fechado e uma sorrindo perfeitamente.", alibi: "Eu simplesmente tenho sorte no timing das fotos, é um talento." },
  "Colocou o celular no silencioso e ignorou 14 ligações da mãe.": { testemunha: "Vi o celular do acusado vibrando sem parar em cima da mesa.", prova: "Uma tela de bloqueio com '14 chamadas perdidas — Mãe'.", alibi: "Eu estava numa reunião importantíssima sobre memes." },
  "Colocou o nome no trabalho em grupo sem ter feito nada.": { testemunha: "O documento tem o histórico de edição, e o nome do acusado não aparece nele.", prova: "Um arquivo compartilhado com zero linhas escritas pelo acusado.", alibi: "Contribuir com energia positiva pro grupo também conta como trabalho." },
  "Disse que a internet caiu no meio da reunião, mas só estava com preguiça.": { testemunha: "O acusado continuou postando nas redes sociais durante a 'queda'.", prova: "Um story publicado 4 minutos depois de 'a internet cair'.", alibi: "Minha internet realmente caiu, só que depois de eu já ter saído." },
  "Copiou a lição e tirou nota maior que quem emprestou.": { testemunha: "Os dois trabalhos eram idênticos, só que um tinha uma nota mais alta.", prova: "Duas provas com os mesmos erros de português, nota vermelha diferente.", alibi: "Eu só usei a lição como inspiração, não como cópia literal." },
  "Esqueceu o microfone aberto e cantou no meio da reunião.": { testemunha: "Todo mundo na chamada ouviu o refrão inteiro, sem querer.", prova: "Uma gravação da reunião com dois minutos de canto a capela.", alibi: "Eu canto melhor quando acho que ninguém está ouvindo." },
  "Imprimiu 80 páginas coloridas na impressora do trabalho.": { testemunha: "A impressora ficou travada por 20 minutos imprimindo algo do acusado.", prova: "Uma pilha de 80 folhas coloridas com receitas de bolo.", alibi: "Tinta colorida é praticamente de graça, é só apertar o botão." },
  "Sentou na janela do ônibus e colocou a bolsa no banco do corredor.": { testemunha: "Fiquei de pé o ônibus inteiro olhando pra bolsa sentada no banco.", prova: "Uma bolsa ocupando um lugar inteiro, num ônibus lotado.", alibi: "Minha bolsa também paga passagem, moralmente falando." },
  "Tirou o sapato no meio do voo.": { testemunha: "O cheiro chegou até três fileiras de distância, seguramente.", prova: "Um par de sapatos embaixo do assento, longe dos pés do dono.", alibi: "Meu pé precisa respirar em altitudes elevadas, é uma questão médica." },
  "Parou no meio da calçada pra olhar o celular.": { testemunha: "Duas pessoas quase esbarraram no acusado, parado feito estátua.", prova: "Uma calçada estreita com um único obstáculo: o acusado, imóvel.", alibi: "Eu recebi uma notícia importantíssima naquele exato segundo." },
  "Fez barulho de obra no apartamento às 8 da manhã de domingo.": { testemunha: "A britadeira começou pontualmente às 8h, no domingo, sem exceção.", prova: "Um vizinho com fone de proteção auricular, tirado de uma caixa de ferramentas.", alibi: "Domingo de manhã é o único horário livre pra pendurar um quadro." },
  "Entrou 30 minutos depois do início da aula com um café na mão.": { testemunha: "O professor parou a explicação quando a porta rangeu, de novo.", prova: "Um copo de café ainda fumegante, às 9h30 de uma aula que começou às 9h.", alibi: "A fila da cafeteria estava histórica naquele dia, juro." },
};
